config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :headings
  resources :facet_leafs
  resources :facets
  resources :sessions
  resources :surrogates_tags
  resources :imports
  resources :resource_collections
  resources :keywords
  resources :se_values
  resources :tags
  resources :surrogate_elements
  resources :surrogates
  resources :users

  root "pages#index"
 
  match '/index', :to => 'surrogates#index', :via => [:get]
  match '/import', :to => 'imports#new', :via => [:get]
  match '/tagged', :to => 'surrogates#tagged', :as => 'tagged', :via => [:get]
  match '/about', :to => 'pages#about', :via => [:get]
  match '/signup', :to => 'users#new', :via => [:get]
  match '/signin', :to => 'sessions#new', :via => [:get]
  match '/signout', :to => 'sessions#destroy', :via => [:get, :post, :delete]
  match '/csv', :to => 'surrogates#csv', :as => 'csv', :via => [:get]
  match '/bib', :to => 'surrogates#bib', :as => 'bib', :via => [:get]
  

end

app/models/facet_leaf.rb
# == Schema Information
#
# Table name: facet_leafs
#
#  id         :integer          not null, primary key
#  facet_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class FacetLeaf < ActiveRecord::Base
  # Appartient a 
  belongs_to :facets
  # A plusieurs
  has_many :headings
  # Doit être unique
  validates :facet_id, :uniqueness => true
end

app/controllers/facet_leafs_controller.rb
class FacetLeafsController < ApplicationController
  before_action :set_facet_leaf, only: [:show, :edit, :update, :destroy]

  # GET /facet_leafs
  # GET /facet_leafs.json
  def index
    @facet_leafs = FacetLeaf.all
  end

  # GET /facet_leafs/1
  # GET /facet_leafs/1.json
  def show
  end

  # GET /facet_leafs/new
  def new
    @facet_leaf = FacetLeaf.new
  end

  # GET /facet_leafs/1/edit
  def edit
  end

  # POST /facet_leafs
  # POST /facet_leafs.json
  def create
    @facet_leaf = FacetLeaf.new(facet_leaf_params)

    respond_to do |format|
      if @facet_leaf.save
        format.html { redirect_to @facet_leaf, notice: 'Facet leaf was successfully created.' }
        format.json { render :show, status: :created, location: @facet_leaf }
      else
        format.html { render :new }
        format.json { render json: @facet_leaf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facet_leafs/1
  # PATCH/PUT /facet_leafs/1.json
  def update
    respond_to do |format|
      if @facet_leaf.update(facet_leaf_params)
        format.html { redirect_to @facet_leaf, notice: 'Facet leaf was successfully updated.' }
        format.json { render :show, status: :ok, location: @facet_leaf }
      else
        format.html { render :edit }
        format.json { render json: @facet_leaf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facet_leafs/1
  # DELETE /facet_leafs/1.json
  def destroy
    @facet_leaf.destroy
    respond_to do |format|
      format.html { redirect_to facet_leafs_url, notice: 'Facet leaf was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facet_leaf
      @facet_leaf = FacetLeaf.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facet_leaf_params
      params.require(:facet_leaf).permit(:facet_id)
    end
end

app/helpers/facet_leafs_helper.rb
module FacetLeafsHelper
end

app/views/facet_leafs/_form.html.erb
<%= form_for(@facet_leaf, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @facet_leaf.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@facet_leaf.errors.count, "error") %> prohibited this facet_leaf from being saved:</h4>

      <ul>
      <% @facet_leaf.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :facet_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :facet_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/facet_leafs/edit.html.erb
<div class="page-header">
  <%= link_to facet_leafs_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @facet_leaf, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing facet_leaf</h1>
</div>

<%= render 'form' %>

app/views/facet_leafs/index.html.erb
<div class="page-header">
  <%= link_to new_facet_leaf_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Facet leaf
  <% end %>
  <h1>Listing facet_leafs</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Facet</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @facet_leafs) do |facet_leaf| %>
            <td><%= facet_leaf.facet_id %></td>
            <td><%= link_to 'Show', facet_leaf %></td>
        <td><%= link_to 'Edit', edit_facet_leaf_path(facet_leaf) %></td>
        <td><%= link_to 'Destroy', facet_leaf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/facet_leafs/new.html.erb
<div class="page-header">
  <%= link_to facet_leafs_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New facet_leaf</h1>
</div>

<%= render 'form' %>

app/views/facet_leafs/show.html.erb
<div class="page-header">
  <%= link_to facet_leafs_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_facet_leaf_path(@facet_leaf), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show facet_leaf</h1>
</div>

<dl class="dl-horizontal">
  <dt>Facet:</dt>
  <dd><%= @facet_leaf.facet_id %></dd>

</dl>