config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :headings
  resources :facet_leafs
  resources :facets
  resources :sessions
  resources :surrogates_tags
  resources :imports
  resources :resource_collections
  resources :keywords
  resources :se_values
  resources :tags
  resources :surrogate_elements
  resources :surrogates
  resources :users

  root "pages#index"
 
  match '/index', :to => 'surrogates#index', :via => [:get]
  match '/import', :to => 'imports#new', :via => [:get]
  match '/tagged', :to => 'surrogates#tagged', :as => 'tagged', :via => [:get]
  match '/about', :to => 'pages#about', :via => [:get]
  match '/signup', :to => 'users#new', :via => [:get]
  match '/signin', :to => 'sessions#new', :via => [:get]
  match '/signout', :to => 'sessions#destroy', :via => [:get, :post, :delete]
  match '/csv', :to => 'surrogates#csv', :as => 'csv', :via => [:get]
  match '/bib', :to => 'surrogates#bib', :as => 'bib', :via => [:get]
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  nom                :string
#  email              :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  encrypted_password :string
#  salt               :string
#

class User < ActiveRecord::Base
  # Défini un accesseur
  attr_accessor :password
  # A plusieurs
  has_many :facets
  # A plusieurs et appartient a
  has_and_belongs_to_many :resource_collections
  # Expression régulière pour le contrôle des emails
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # Conditions de validation de certains champs.
  validates :nom, 
    :presence => true, # Doit être présent
    :length => { :maximum => 50 } # Longueur max 50 caractères 
  validates :email, 
    :presence => true, # Doit être présent
    :format => { :with => email_regex }, # Controle le format avec le regex
    :uniqueness => { :case_sensitive => false } # Doit être unique, ne prend pas en compte les majuscules.
  validates :password, 
    :presence => true, # Doit être présent
    :confirmation => true, # Doit être confirmé (renseigné une seconde fois)
    :length => { :within => 6..40 } # Taille min 6 caractères, max 40 caractères.
  before_save :encrypt_password # Avant d'enregistrer, crypter le mot de passe.
  
  # Vérifie que la concordance du mot de passe renseigné avec le vrai.
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  # Permet l'authentification d'un utilisateur
  def self.authenticate(email, submitted_password)
    # Cherche l'utilisateur avec l'email renseigné
    user = find_by_email(email)
    # Echoue si introuvable
    return nil if user.nil?
    # Identifie l'utilisateur si le mot de passe renseigné est correct
    return user if user.has_password?(submitted_password)
  end

  # 
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  # Permet de crypter le mot de passe
  private def encrypt_password
    # Créé une donnée supplémentaire aléatoire pour la sécurité du mot de passe.
    # = Salage
    self.salt = make_salt if new_record?
    # Crypte le mot de passe.
    self.encrypted_password = encrypt(password)
  end

  # Crypte le mot de passe avec le "salage".
  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  # Créé le salage avec le temps à l'instant de la création. (YY/MM/JJ/h/m/s)
  def make_salt
    secure_hash("#{Time.new.utc}--#{password}")
  end
  
  # Fonction d'encryptage / sécurité
  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # Pour l'affichage des utilisateurs
  def show
    # On récupère l'utilisateur sélectionné
    @user = User.find(params[:id])
    @title = @user.nom
  end

  def new
    @user = User.new
    @title = "Sign up!"
  end
  
  # Pour l'inscription  d'un utilisateur
  def create
    # On créé un compte avec les champs renseigné par l'utilisateur
    @user = User.new(user_params)
    # Si ça fonctionne
    if @user.save
      sign_in @user
      # On le renvoi sur la page d'accueil avec un message de confirmation.
      redirect_to root_path, notice: "You are now registered !"
    # Sinon on rafraichi la page
    else
      @titre = "Sign Up!"
      render 'new'
    end
  end

  # Défini les champs modifiables dans la table USER
  def user_params
    params.require(:user).permit(:nom, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<!-- Affichage de la barre de navigation -->

<%= render 'layouts/signup_navbar' %>

<!-- Formulaire d'inscription -->

<h1>Sign Up!</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up!" %>
  </div>
<% end %>

<!-- Si l'utilisateur est déjà inscrit on le guide vers la page
d'identification -->

<p>Already registered ? <%= link_to "Sign in!", '/signin' %></p>

app/views/users/show.html.erb
<!-- Affichage de la barre de navigation -->

<%= render 'layouts/user_navbar' %>

<!-- Affichage du nom de l'utilisateur comme en-tête -->

<h2 align="center"><%= @user.nom %><small> personal space</small></h2>
<div style="margin-bottom: 15px">

<!-- Choix entre la consultation de ses information
ou de ses ressources (collections/classifications/ressources) -->

  <h5>My informations | My resources</h5>
</div>

<!-- Découpe la page en deux. 
Panel 1 : Gestion des collections
-->

<div class="row">
  <div class="col-sm-6">
    <div class="panel panel-info">
      <div class="panel-heading">
        <b>MY COLLECTIONS</b>
      </div>
      <div class="panel-body">
        <% @user.resource_collections.order(:collection_name).each do |rc| %>
	<div class="row">
	  <div class="col-sm-3">
	    <h4><%= rc.collection_name %></h4>
	  </div>
	  <div class="col-sm-9" align="right">
	    <div class="btn-group" role="group">
	      <%= link_to "Show", surrogates_path(:collection_id => rc.id), :class => "btn btn-success", style: "color: #fff" %>
	      <%= link_to "Edit", "#", :class => "btn btn-info", style: "color: #fff" %>
	      <%= link_to "Delete", resource_collection_path(rc), method: :delete, data: {confirm: "Are you sure?" }, :class => "btn btn-danger", style: "color: #fff" %>
	    </div>
	  </div>
	</div>
	<% end %>
      </div>
    </div>
  </div>

<!-- Panel 2 : Gestion des classifications
-->

  <div class="col-sm-6">
    <div class="panel panel-info">
      <div class="panel-heading">
        <b>MY CLASSIFICATIONS</b>
      </div>
      <div class="panel-body">
        ...
      </div>
    </div>
  </div>
</div>