config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :headings
  resources :facet_leafs
  resources :facets
  resources :sessions
  resources :surrogates_tags
  resources :imports
  resources :resource_collections
  resources :keywords
  resources :se_values
  resources :tags
  resources :surrogate_elements
  resources :surrogates
  resources :users

  root "pages#index"
 
  match '/index', :to => 'surrogates#index', :via => [:get]
  match '/import', :to => 'imports#new', :via => [:get]
  match '/tagged', :to => 'surrogates#tagged', :as => 'tagged', :via => [:get]
  match '/about', :to => 'pages#about', :via => [:get]
  match '/signup', :to => 'users#new', :via => [:get]
  match '/signin', :to => 'sessions#new', :via => [:get]
  match '/signout', :to => 'sessions#destroy', :via => [:get, :post, :delete]
  match '/csv', :to => 'surrogates#csv', :as => 'csv', :via => [:get]
  match '/bib', :to => 'surrogates#bib', :as => 'bib', :via => [:get]
  

end

app/models/import.rb
# == Schema Information
#
# Table name: imports
#
#  id             :integer          not null, primary key
#  attachment     :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  collection_id  :integer
#  new_collection :string
#

class Import < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # On utilise cet uploader pour ce model
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController

  def new
    @import = Import.new
  end

  # Pour l'importation d'un fichier BibTeX et son traitement.
  def create
    # Récupère le fichier et l'enregistre temporairement en BDD
    @import = Import.new(import_params)
    # Récupère le nom du fichier .bib sans l'extension.
    @fName = @import.attachment.to_s.split('/').last.split('.').first
    # Parse le fichier .bib et l'enregistre dans une variable.
    @bib = BibTeX.open("./public/#{@import.attachment.to_s}")

    # Si l'utilisateur spécifie un nom pour une nouvelle collection 
    if @import.new_collection != ""
      # Si l'utilisateur est enregistré, on créer cette collection
      if !current_user.nil?
        User.where(:id => current_user.id).first.resource_collections << ResourceCollection.create(:user_id => current_user.id, :collection_name => @import.new_collection)
      end
    end
   
    # Tant que le fichier contient des entrées bibtex (surrogate)...
    i = 0
    while @bib[i] != nil do
      # ... Convertie l'entrée bibtex en string
      @entry = @bib[i].to_s
      # Si l'utilisateur n'est pas enregistré
      if current_user.nil? 
        # On enregistre les surrogates dans la collection par défaut
        ResourceCollection.where(:collection_name => "Default").first.surrogates << Surrogate.create(:entry_type => @bib[i].type, :entry_key => @bib[i].key, :doi => @bib[i]['doi'], :url => @bib[i]['url'])
      # Sinon, s'il est enregistré
      else
        # Si l'utilisateur sélectionne une collection 
        if @import.collection_id != nil
          # Et s'il entre un nom de nouvelle collection
          if @import.new_collection != ""
            # On enregistre ces surrogates dans la nouvelle collection
	    # et non pas dans celle sélectionnée.
            ResourceCollection.where(:user_id => current_user.id, :collection_name => @import.new_collection).first.surrogates << Surrogate.create(:entry_type => @bib[i].type, :entry_key => @bib[i].key, :doi => @bib[i]['doi'], :url => @bib[i]['url'])
          # S'il n'entre pas de nom de nouvelle collection
          else 
	    # On enregistre ces surrogates dans la collection sélectionnée.
	    ResourceCollection.where(:id => @import.collection_id).first.surrogates << Surrogate.create(:entry_type => @bib[i].type, :entry_key => @bib[i].key, :doi => @bib[i]['doi'], :url => @bib[i]['url'])
          end
        # Si l'utilisateur ne sélectionne pas de collection
        # mais spécifie un nom de nouvelle collection
        elsif @import.new_collection != ""
          #On enregistre les surrogates dans la nouvelle collection.
          ResourceCollection.where(:user_id => current_user.id, :collection_name => @import.new_collection).first.surrogates << Surrogate.create(:entry_type => @bib[i].type, :entry_key => @bib[i].key, :doi => @bib[i]['doi'], :url => @bib[i]['url'])
        # Sinon, si l'utilisateur n'a rien spécifié on enregistre
        # les surrogates dans la collection par défaut.
        else
          ResourceCollection.where(:collection_name => "Default").first.surrogates << Surrogate.create(:entry_type => @bib[i].type, :entry_key => @bib[i].key, :doi => @bib[i]['doi'], :url => @bib[i]['url'])
        end
      end
      
      @srg = Surrogate.last
      # ... Parcours chaque champs d'une entrée
      j = 0
      while @bib[i].entries[j] != nil do
        @type = 0
        # Enregistre le nom du champ s'il existe
        if (@sField = @bib[i].entries[j].to_s.split('"')[0].split(/\W+/)[1]).nil?
	  @sField = @bib[i].entries[j].to_s.split('"')[1]
          @type = 1
	end
	k = 0 
        # Si le champ parcouru est le champ keyword on récupère les
	# valeurs entre les séparateurs "," et ";"
	if @sField === "keywords"
	  @sValue = @bib[i].entries[j].to_s.split('"')[1].split(/;|,/)
        # Si le champ parcouru est le champ author ou editor on
	# spécifie la façon de récupérer correctement les noms.
	elsif @sField === "author" || @sField === "editor"
	  @sValue = @bib[i].entries[j].to_s.split('"').delete_if{|e| e === ", "}.delete_if{|e| e === ">]"}
	  k = 1 
        # Si le champ parcouru est le champ month on récupère sa
	# valeur (cette partie est un bug fix de la librairie)
	elsif @sField === "month"
	  @sValue = @bib[i].entries[j].to_s.split(/:|>/)[4].split("",1)
        # Si le champ parcouru est le champ abstract on fait attention
	# à ne pas couper le résumé en morceaux à cause des vigules.
	elsif @sField === "abstract"
	  @sValue = @bib[i].entries[j].to_s.split('"')
	  k = 1 
	# Par défaut on considère que les différentes valeurs sont 
	# séparées pas des virgules.
	elsif @type === 1 
          @sValue = @bib[i].entries[j].to_s.split('"')[3].split(',')
	else
          @sValue = @bib[i].entries[j].to_s.split('"')[1].split(',')
	end
	# On sauvegarde le champ keyword pour créer les tags après avoir
	# traité le reste.
	@sKeywords = @bib[i]['keywords'].to_s.split(/;|,/)
        # Enregistre le surrogateElement dans la BDD
        @srgElmt = @srg.surrogate_elements.create(:field_name => @sField)
        # Enregistre tout les valeurs du champ parcouru dans la BDD
	while @sValue[k] != nil do
          @seValue = @srgElmt.se_values.create(:value => @sValue[k].strip, :surrogate_id => @srgElmt.surrogate_id)
          k = k+1
	end # While end
        j = j+1
      end # While End
      k = 1
      while @sKeywords[k] != nil do
        @keyword = @srg.keywords.create(:keywordName => @sKeywords[k].strip)
        @tag = @srg.tag_list.add(@sKeywords[k].strip)
        k = k+1
      end # While End
      @srg.save
      i = i+1
    end # While end

    # Supprime les fichiers temporaires (.bib)
    FileUtils.rm_rf(Dir.glob('./public/uploads/tmp/*'))
    # Renvoie sur la page de navigation
    redirect_to surrogates_path, notice: "The BibTeX file #{@fName}.bib has been imported. Thank you for your contribution"
  end

#------ INACTIF ------#

  # Supprimer un fichier .bib
  def destroy
    @import = Import.find(params[:id])
    @import.destroy
    redirect_to surrogates_path, notice: "The BibTeX file #{@fName}.bib has been removed."
  end

  # Définie les champs modifiable de IMPORT 
  private def import_params
    params.require(:import).permit(:attachment, :collection_id, :new_collection)
  end

  # Définie les champs modifiable de SURROGATE
  private def surrogate_params
    params.require(:surrogate).permit(:entry_key, :entry_type, :doi, :url)
  end

  # Définie les champs modifiable de SURROGATE_ELEMENT
  private def surrogateElement_params
    params.require(:surrogateElement).permit(:field_name)
  end

  # Définie les champs modifiable de SE_VALUE
  private def seValues_params
    params.require(:seValues).permit(:value)
  end
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/imports/_form.html.erb
<%= form_for(@import) do |f| %>
  <% if @import.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@import.errors.count, "error") %> prohibited this import from being saved:</h2>

      <ul>
      <% @import.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/imports/create.html.erb
<h1>Imports#create</h1>
<p>Find me in app/views/imports/create.html.erb</p>

app/views/imports/destroy.html.erb
<h1>Imports#destroy</h1>
<p>Find me in app/views/imports/destroy.html.erb</p>

app/views/imports/edit.html.erb
<h1>Editing Import</h1>

<%= render 'form' %>

<%= link_to 'Show', @import %> |
<%= link_to 'Back', imports_path %>

app/views/imports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Imports</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @imports.each do |import| %>
      <tr>
        <td><%= link_to 'Show', import %></td>
        <td><%= link_to 'Edit', edit_import_path(import) %></td>
        <td><%= link_to 'Destroy', import, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Import', new_import_path %>

app/views/imports/new.html.erb
<!-- Affichage de la barre de navigation -->

<%= render 'layouts/default_navbar' %>

<% if !@import.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @import.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<!-- Formulaire d'envoie de fichier au serveur -->

<div class="well">
  <%= form_for @import, html: { multipart: true } do |f| %>
    <%= f.label "File to import" %>
    <%= f.file_field :attachment %>

<!-- Si l'utilisateur est identifié, on lui propose
d'ajouter ses ressources à une collection existante
ou d'en créer une -->

    <% if signed_in? %>
    <%= f.label "Add to :", style: "margin-top: 10px" %>
    <br />
    <div class="row">
    <div class="col-sm-2" align="left">
      <%= f.select :collection_id, options_from_collection_for_select(ResourceCollection.where(:user_id => current_user), "id", "collection_name"), {:prompt => "- Select a collection -"}, class: "form-control", style: "input-lg" %>
    </div>
    <div class="col-sm-3">
      <%= f.text_field :new_collection, placeholder: "Create a new one", class: "form-control" %>
    </div>
    </div>
    <br />
    <% end %>
    <%= f.submit "Import", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/imports/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_import_path(@import) %> |
<%= link_to 'Back', imports_path %>