config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :headings
  resources :facet_leafs
  resources :facets
  resources :sessions
  resources :surrogates_tags
  resources :imports
  resources :resource_collections
  resources :keywords
  resources :se_values
  resources :tags
  resources :surrogate_elements
  resources :surrogates
  resources :users

  root "pages#index"
 
  match '/index', :to => 'surrogates#index', :via => [:get]
  match '/import', :to => 'imports#new', :via => [:get]
  match '/tagged', :to => 'surrogates#tagged', :as => 'tagged', :via => [:get]
  match '/about', :to => 'pages#about', :via => [:get]
  match '/signup', :to => 'users#new', :via => [:get]
  match '/signin', :to => 'sessions#new', :via => [:get]
  match '/signout', :to => 'sessions#destroy', :via => [:get, :post, :delete]
  match '/csv', :to => 'surrogates#csv', :as => 'csv', :via => [:get]
  match '/bib', :to => 'surrogates#bib', :as => 'bib', :via => [:get]
  

end

app/models/facet.rb
# == Schema Information
#
# Table name: facets
#
#  id         :integer          not null, primary key
#  facet_name :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Facet < ActiveRecord::Base
  # Appartient à
  belongs_to :users
  # A plusieurs
  has_many :facet_leafs, :dependent => :destroy
  has_many :headings
  # Doit être unique
  validates :facet_name, :uniqueness => true
end

app/models/facet_leaf.rb
# == Schema Information
#
# Table name: facet_leafs
#
#  id         :integer          not null, primary key
#  facet_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class FacetLeaf < ActiveRecord::Base
  # Appartient a 
  belongs_to :facets
  # A plusieurs
  has_many :headings
  # Doit être unique
  validates :facet_id, :uniqueness => true
end

app/models/heading.rb
# == Schema Information
#
# Table name: headings
#
#  id            :integer          not null, primary key
#  heading_name  :string
#  facet_leaf_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  abbreviation  :string
#

class Heading < ActiveRecord::Base
  # Appartient a
  belongs_to :facet_leafs
  # A plusieurs et appartient à 
  has_and_belongs_to_many :surrogates
  # Doit être unique
  validates :heading_name, :uniqueness => true
end

app/models/import.rb
# == Schema Information
#
# Table name: imports
#
#  id             :integer          not null, primary key
#  attachment     :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  collection_id  :integer
#  new_collection :string
#

class Import < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # On utilise cet uploader pour ce model
end

app/models/keyword.rb
# == Schema Information
#
# Table name: keywords
#
#  id           :integer          not null, primary key
#  keywordName  :string
#  surrogate_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Keyword < ActiveRecord::Base
  # Appartient a 
  belongs_to :surrogates
end

app/models/se_value.rb
# == Schema Information
#
# Table name: se_values
#
#  id                   :integer          not null, primary key
#  value                :string
#  surrogate_element_id :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  surrogate_id         :integer
#

class SeValue < ActiveRecord::Base
  # Appartient a
  belongs_to :surrogate_element
  belongs_to :surrogates

  # Fonction de recherche de terme pour le "searching"
  def self.search(query)
    where("value like ?", "%#{query}%")
  end

end

app/models/surrogate.rb
# == Schema Information
#
# Table name: surrogates
#
#  id                     :integer          not null, primary key
#  entry_type             :string
#  entry_key              :string
#  doi                    :string
#  url                    :string
#  resource_collection_id :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Surrogate < ActiveRecord::Base
  # Peut être taggué
  acts_as_taggable_on :tags
  # A plusieurs et appartient a
  has_and_belongs_to_many :resource_collections
  has_and_belongs_to_many :headings
  # A plusieurs
  has_many :surrogate_elements, :dependent => :destroy
  has_many :se_values
  has_many :keywords, :dependent => :destroy
  # Les champs suivant ne doivent pas être vide ou null
  validates :entry_type, :presence => true
  validates :entry_key, :presence => true

  # Fonction de recherche de terme pour le "searching"
  def self.search(query)
    where("entry_key like ?", "%#{query}%")
  end

end

app/models/surrogates_tag.rb
# == Schema Information
#
# Table name: surrogates_tags
#
#  surrogate_id :integer
#  tag_id       :integer
#

class SurrogatesTag < ActiveRecord::Base
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id             :integer          not null, primary key
#  name           :string
#  taggings_count :integer          default(0)
#

class Tag < ActiveRecord::Base
  # A plusieurs et appartient a
  has_and_belongs_to_many :surrogates
  # Doit être unique
  validates :tag_name, :uniqueness => true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  nom                :string
#  email              :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  encrypted_password :string
#  salt               :string
#

class User < ActiveRecord::Base
  # Défini un accesseur
  attr_accessor :password
  # A plusieurs
  has_many :facets
  # A plusieurs et appartient a
  has_and_belongs_to_many :resource_collections
  # Expression régulière pour le contrôle des emails
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # Conditions de validation de certains champs.
  validates :nom, 
    :presence => true, # Doit être présent
    :length => { :maximum => 50 } # Longueur max 50 caractères 
  validates :email, 
    :presence => true, # Doit être présent
    :format => { :with => email_regex }, # Controle le format avec le regex
    :uniqueness => { :case_sensitive => false } # Doit être unique, ne prend pas en compte les majuscules.
  validates :password, 
    :presence => true, # Doit être présent
    :confirmation => true, # Doit être confirmé (renseigné une seconde fois)
    :length => { :within => 6..40 } # Taille min 6 caractères, max 40 caractères.
  before_save :encrypt_password # Avant d'enregistrer, crypter le mot de passe.
  
  # Vérifie que la concordance du mot de passe renseigné avec le vrai.
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  # Permet l'authentification d'un utilisateur
  def self.authenticate(email, submitted_password)
    # Cherche l'utilisateur avec l'email renseigné
    user = find_by_email(email)
    # Echoue si introuvable
    return nil if user.nil?
    # Identifie l'utilisateur si le mot de passe renseigné est correct
    return user if user.has_password?(submitted_password)
  end

  # 
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  # Permet de crypter le mot de passe
  private def encrypt_password
    # Créé une donnée supplémentaire aléatoire pour la sécurité du mot de passe.
    # = Salage
    self.salt = make_salt if new_record?
    # Crypte le mot de passe.
    self.encrypted_password = encrypt(password)
  end

  # Crypte le mot de passe avec le "salage".
  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  # Créé le salage avec le temps à l'instant de la création. (YY/MM/JJ/h/m/s)
  def make_salt
    secure_hash("#{Time.new.utc}--#{password}")
  end
  
  # Fonction d'encryptage / sécurité
  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/facets_helper.rb
module FacetsHelper
end

app/helpers/headings_helper.rb
module HeadingsHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_about_navbar.html.erb
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "BibTag v2.0", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", surrogates_path %></li>
          <li class="active"><%= link_to "About", about_path %></li>
	  <% if signed_in? %>
	  <li><%= link_to "My space", user_path(current_user) %></li>
	  <li><%= link_to "Sign Out", signout_path, :method => :delete %></li>
	  <% else %>
          <li><%= link_to "Sign Up!", signup_path %></li>
          <li><%= link_to "Sign In", signin_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/_default_navbar.html.erb
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "BibTag v2.0", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", surrogates_path %></li>
          <li><%= link_to "About", about_path %></li>
	  <% if signed_in? %>
	  <li><%= link_to "My space", user_path(current_user) %></li>
	  <li><%= link_to "Sign Out", signout_path, :method => :delete %></li>
	  <% else %>
          <li><%= link_to "Sign Up!", signup_path %></li>
          <li><%= link_to "Sign In", signin_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/_footer.html.erb
<footer style="color: #ccc">
  <h6>ENSTA Brest - Pole STIC - 2015<br> Application créée par Ribaud Vincent & Gourvénec Matthieu</h6>
</footer>

app/views/layouts/_header.html.erb
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>BibTag v2.0</title>
<%= render 'layouts/stylesheets' %>
</head>

app/views/layouts/_home_navbar.html.erb
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "BibTag v2.0", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", surrogates_path %></li>
          <li><%= link_to "About", about_path %></li>
	  <% if signed_in? %>
	  <li><%= link_to "My space", user_path(current_user) %></li>
	  <li><%= link_to "Sign Out", signout_path, :method => :delete %></li>
	  <% else %>
          <li><%= link_to "Sign Up!", signup_path %></li>
          <li><%= link_to "Sign In", signin_path %></li>
          <% end %>
	</ul>
      </div>
    </div>
  </nav>

app/views/layouts/_signin_navbar.html.erb
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "BibTag v2.0", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", surrogates_path %></li>
          <li><%= link_to "About", about_path %></li>
	  <% if signed_in? %>
	  <li><%= link_to "My space", user_path(current_user) %></li>
	  <li><%= link_to "Sign Out", signout_path, :method => :delete %></li>
	  <% else %>
          <li><%= link_to "Sign Up!", signup_path %></li>
          <li class="active"><%= link_to "Sign In", signin_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/_signup_navbar.html.erb
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "BibTag v2.0", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", surrogates_path %></li>
          <li><%= link_to "About", about_path %></li>
	  <% if signed_in? %>
	  <li><%= link_to "My space", user_path(current_user) %></li>
	  <li><%= link_to "Sign Out", signout_path, :method => :delete %></li>
	  <% else %>
          <li class="active"><%= link_to "Sign Up!", signup_path %></li>
          <li><%= link_to "Sign In", signin_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/_stylesheets.html.erb
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

app/views/layouts/_user_navbar.html.erb
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "BibTag v2.0", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", surrogates_path %></li>
          <li><%= link_to "About", about_path %></li>
	  <% if signed_in? %>
	  <li class="active"><%= link_to "My space", user_path(current_user) %></li>
	  <li><%= link_to "Sign Out", signout_path, :method => :delete %></li>
	  <% else %>
          <li><%= link_to "Sign Up!", signup_path %></li>
          <li><%= link_to "Sign In", signin_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/header' %>
<body>
  <div class="container" style="margin-bottom: 50px">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
<div class="navbar navbar-inverse navbar-fixed-bottom" style="border-top: 1px solid #ccc">
<div class="container">
<%= render 'layouts/footer' %>
</div>
</div>
</html>

app/views/pages/about.html.erb
<%= render 'layouts/about_navbar' %>
<div style="margin-bottom: 10px; border-bottom: 1px solid #ccc">
  <h1>BibTag <small>v2.0</small></h1>
</div>
<h5>BibTag is a Ruby on Rails application made for facets classification of resources.
<br />
<br />
Initiated by Vincent Ribaud from the ENSTA STIC research center, le project finally cames out with the help of Matthieu Gourvénec an IT student.</h5>

app/views/pages/index.html.erb
<!DOCTYPE html>
<!-- CF : layouts/application.html.erb -->

<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>BibTag v2.0</title>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<!-- Ajout d'une image de fond au body -->
<body background="images/bibtagbg.png">
  <div class="container" style="margin-top: 120px; margin-bottom: 150px">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>
<%= render 'layouts/default_navbar' %>

<!-- Message d'accroche -->
<h1 style="color: #fff; margin-bottom: 50px" align="center"><i>"The best online bibliography, find whatever you need !"</i></h1>

<!-- Boutton vers l'import -->
  <div align="center"><%= button_to "Contribute", '/import', class: "btn btn-info btn-lg", style: "margin-top: 8px", method: "get" %></div>

<h1 align="center" style="color: #fff">OR</h1> 
 
<!-- Barre de recherche par mot clef -->
 <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6" style="margin-top: 8px"><%= form_tag surrogates_path, :method => 'get' do %>
    <div class="input-group add-on">
      <%= text_field_tag :search, params[:search], :class => "form-control input-lg" %>
      <div class="input-group-btn">
      <%= submit_tag "Search", :name => nil, :class => "btn btn-success btn-lg" %>
      </div>
    </div>
    <% end %>
  </div>
</div>
<br />
  </div>
</body>

<!-- CF : layouts/_footer.html.erb -->

<div class="navbar navbar-inverse navbar-fixed-bottom" style="border-top: 1px solid #ccc">
<div class="container footer">
<footer style="color: #ccc">
  <h6>ENSTA Brest - Pole STIC - 2015<br> Application créée par Ribaud Vincent & Gourvénec Matthieu</h6>
</footer>
</div>
</div>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> during your registration</h2>
    <p>Thanks to fix thoses fields :</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>